version: '3'

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8501:8501"
    command: uv run streamlit run server/LOGIN.py
    volumes:
      - ./server/assets:/server/assets
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - /etc/ssl:/etc/ssl 